#!/usr/bin/python3
import sys

def factor(n):
    """Factor the given number n"""
    i = 2
    while i * i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            return f"{n}={i}*{n}"
    return f"{n} is prime"

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <file>")
        sys.exit(1)

    with open(sys.argv[1]) as f:
        for line in f:
            n = int(line.strip())
            print(factor(n))
