#!/usr/bin/python3
from sys import argv
from linecache import getline


def first_prime_factor(n: int) -> int:
    if n <= 3:
        return (2)
    if n % 2 == 0:
        return (2)
    if n % 3 == 0:
        return (3)
    limit = int(n ** 0.5)
    if limit % 2 == 0:
        limit = limit + 1
    i, j = 5, limit
    while i <= j:
        if n % i == 0:
            return (i)
        if n % (i + 2) == 0:
            return (i + 2)
        if n % j == 0:
            return (j)
        if n % (j - 2) == 0:
            return (j - 2)
        i += 6
        j -= 4
    return (1)


if __name__ == "__main__":
    line = 1
    while True:
        line_str = getline(argv[1], line)
        if (len(line_str) == 0):
            break
        num = int(line_str[:-1])
        factor = first_prime_factor(num)
        print("{}={}*{}".format(num, num // factor, factor))
        line += 1
